# Generated by Django 3.2 on 2021-04-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='metalprecioso',
            field=models.BooleanField(blank=None, default=False),
        ),
        migrations.AddField(
            model_name='mineral',
            name='region',
            field=models.TextField(choices=[(1, 'Region Occidental'), (2, 'Region Central'), (3, 'Region Oriental')], default='who_cares', max_length=40),
        ),
    ]
