# Generated by Django 3.2 on 2021-04-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localdb', '0003_alter_mineral_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='region',
            field=models.TextField(blank=None, choices=[('Region Occidental', 'Occidente'), ('Region Central', 'Centro'), ('Region Oriental', 'Oriente')], default='who_cares', max_length=40),
        ),
    ]
