# Generated by Django 3.2 on 2021-04-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localdb', '0004_alter_mineral_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='typeof',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('metalífero', 'Metlífero'), ('nometalífero', 'Nometalífero')], default='unknown', max_length=15),
        ),
    ]
