# Generated by Django 3.2 on 2021-05-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localdb', '0005_alter_mineral_typeof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, default='unknown', max_length=50)),
                ('Firma', models.CharField(blank=None, default='unknown', max_length=50)),
                ('Group', models.TextField(blank=None, default='unknown')),
                ('main_res', models.CharField(blank=None, default='Copper', max_length=20)),
                ('region', models.TextField(blank=None, default='Around there')),
                ('life_cycle', models.FloatField(blank=None, default='undetermined')),
            ],
        ),
        migrations.AlterField(
            model_name='mineral',
            name='region',
            field=models.TextField(blank=None, choices=[('unknown', 'Unknown'), ('Region Occidental', 'Occidente'), ('Region Central', 'Centro'), ('Region Oriental', 'Oriente')], default='unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='typeof',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('metalífero', 'Metalífero'), ('nometalífero', 'Nometalífero')], default='unknown', max_length=15),
        ),
    ]
