# Generated by Django 3.2 on 2021-05-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localdb', '0007_alter_proyects_life_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyects',
            name='Firma',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='proyects',
            name='Group',
            field=models.TextField(default='unknown'),
        ),
        migrations.AlterField(
            model_name='proyects',
            name='life_cycle',
            field=models.FloatField(default=69),
        ),
        migrations.AlterField(
            model_name='proyects',
            name='name',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='proyects',
            name='region',
            field=models.TextField(default='Around there'),
        ),
    ]
