# Generated by Django 3.2 on 2021-05-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localdb', '0008_auto_20210503_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyects',
            name='life_cycle',
            field=models.FloatField(blank=True),
        ),
    ]
