# Generated by Django 3.2 on 2021-05-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localdb', '0009_alter_proyects_life_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyects',
            name='Group',
            field=models.TextField(blank=True, default='unknown'),
        ),
    ]
