# Generated by Django 3.2 on 2021-05-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localdb', '0012_alter_proyects_life_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate', models.CharField(choices=[('unknown', 'Unknown'), ('Arido', 'Arid'), ('Seco', 'Dry'), ('Humedo', 'Humid')], default='unknown', max_length=50)),
                ('altitude', models.FloatField()),
                ('embossment', models.CharField(choices=[('unknown', 'Unknown'), ('llano', 'Plain'), ('Montañoso', 'Mountain'), ('Desierto', 'Desert')], default='unknown', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='mineral',
            name='region',
            field=models.TextField(blank=None, choices=[('unknown', 'Unknown'), ('West Region', 'Occident'), ('Region Central', 'Center'), ('East Region', 'Orient')], default='unknown', max_length=40),
        ),
    ]
